name: checkov

on:
  push:
    branches:
      - main
    paths:
      - "template.yaml"
      - "checkov-policies/**"
  pull_request:
    branches:
      - main
    paths:
      - "template.yaml"
      - "checkov-policies/**"
      - ".github/workflows/checkov.yml"

  workflow_dispatch:

jobs:
  scan-orch:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@59b9d7edfcad5b87fbe3f473a9a134a721ad03f8 # v12.3119.0
        with:
          file: template.yaml
          framework: cloudformation
          quiet: true
          output_format: cli,sarif
          output_file_path: console,results.sarif
          external_checks_dirs: checkov-policies

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v3.25.12v3
        with:
          sarif_file: results.sarif
          category: orch-sam
